name: devops-hello-world

services:
  web-dev:
    build:
      context: .
      dockerfile: Dockerfile
    image: cmcrumley/devops-hello-world:dev
    env_file: [.env.dev]
    ports: ["8000:8000"]
    profiles: ["dev"]

  web-staging:
    image: cmcrumley/devops-hello-world:latest
    env_file: [.env.staging]
    pull_policy: always
    ports: ["8001:8000"]
    profiles: ["staging"]
    restart: unless-stopped

  web-prod:
    image: cmcrumley/devops-hello-world:latest
    env_file: [.env.prod]
    pull_policy: always
    ports: ["8002:8000"]
    profiles: ["prod"]
    restart: unless-stopped