name: Test & Publish Docker

on:
  push:
    branches: ["main"]
    with:
      images: ${{ secrets.DOCKERHUB_USERNAME }}/devops-hello-world
      tags: |
        type=raw,value=latest,enable={{is_default_branch}}
        type=ref,event=tag                    # v0.1.0
        type=semver,pattern={{version}}       # 0.1.0
        type=semver,pattern={{major}}.{{minor}}  # 0.1
        type=sha
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          if [ -f requirements-dev.txt ]; then pip install -r requirements-dev.txt; fi

      - name: Run tests
        env:
          PYTHONPATH: ${{ github.workspace }}
        run: python -m pytest -q

      - name: pip-audit (deps)
        run: |
          python -m pip install --upgrade pip pip-audit
          pip-audit -r requirements.txt --strict

  docker:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Extract Docker metadata (tags/labels)
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ secrets.DOCKERHUB_USERNAME }}/devops-hello-world
          tags: |
            type=raw,value=latest,enable={{is_default_branch}}
            type=ref,event=tag
            type=sha

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .              # only send project_1 as build context
          dockerfile: ./Dockerfile
          platforms: linux/amd64
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Trivy image scan (fail on HIGH/CRITICAL)
        uses: aquasecurity/trivy-action@0.24.0
        with:
          image-ref: ${{ secrets.DOCKERHUB_USERNAME }}/devops-hello-world:latest
          format: table
          severity: HIGH,CRITICAL
          ignore-unfixed: true
          exit-code: '1'